version: '3.9'

services:
  #build nginx server
  nginx_lb:
    container_name: nginx_lb
    image: nginx:1.25
    hostname: 'nginx'
    ports: 
     - "8080:80"
     - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./nginx/ssl/localhost.key:/etc/ssl/certs/localhost.key:ro

  #build postgres database
  postgres_db:
    container_name: postgres_db
    hostname: 'postgres'
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
  
volumes:
  postgres-data:
    driver: local